// Emits CREATE TABLE statements for a MySQL database shaped to receive the
// exact same backup JSON that artifacts/api-server/src/lib/fullBackup.ts
// exports from Postgres today. This does NOT touch this app's Postgres
// database or run against it in any way — it only reads the plain metadata
// in ./tableMeta.ts (itself derived from lib/db/src/schema/medschool.ts) and
// prints SQL text.
//
// Usage:
//   pnpm --filter @workspace/scripts run generate:mysql-schema > mysql-schema.sql
//   pnpm --filter @workspace/scripts run generate:mysql-schema -- --scope=content
//
// This is the schema a future MySQL importer (./restore.ts) inserts into —
// run it against the new MySQL database once, before the first restore.
//
// Deliberate simplifications, matching how the Postgres schema itself works
// today (see the zero `.references()` calls in medschool.ts — this app has
// never used database-level foreign keys, only the application-level
// FK_CHECKS validation that fullBackup.ts and restore.ts both do):
//   - No FOREIGN KEY constraints. Relationships are validated at the JSON
//     layer (see validate.ts), the same way the Postgres restore already
//     works — a DB-level FK here would just fail on any row that isn't in
//     data[]-order, which is not a thing this schema needs to guard against.
//   - No UNIQUE indexes (e.g. med_users.email) — nothing about restoring a
//     one-time backup depends on them, and adding them here without also
//     replicating every unique index in medschool.ts would be half a job.
//     Add real indexes as part of actually standing up MySQL for production
//     use, not from this generator.
//   - numeric(precision, scale) collapses to one generous DECIMAL(14,4) —
//     every numeric column in the schema fits well inside that (the widest
//     is `numeric(12, 2)`) and the backup file doesn't carry the original
//     precision/scale, so this is deliberately generous rather than guessed
//     per-column.

import { pathToFileURL } from "node:url";
import { CONTENT_TABLE_SPECS, USER_TABLE_SPECS, NO_AUTO_INCREMENT, type ColumnMeta, type MysqlTableSpec } from "./tableMeta.js";

// True only when this file is the process's actual entry point (run via
// `tsx generateSchema.ts` / `pnpm run generate:mysql-schema`), false when
// it's imported as a module (e.g. schemaPrep.ts importing createTableSql).
// Without this guard, importing createTableSql would also run the CLI's
// main() below as a side effect of the import.
function isEntryPoint(): boolean {
  try {
    return !!process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
  } catch {
    return false;
  }
}

function mysqlColumnType(col: ColumnMeta): string {
  if (col.array) return "JSON";
  switch (col.type) {
    case "int":
      return "INT";
    case "boolean":
      return "TINYINT(1)";
    case "timestamp":
      return "DATETIME(3)";
    case "date":
      return "DATE";
    case "numeric":
      return "DECIMAL(14,4)";
    case "json":
      return "JSON";
    case "text": {
      // A TEXT/BLOB column can't be used as a MySQL primary key without an
      // explicit prefix length — the one case here is platformSettings.key.
      return "VARCHAR(255)";
    }
    default:
      return "TEXT";
  }
}

// text columns that aren't part of the primary key can stay full TEXT
// (unbounded), which VARCHAR(255) above would wrongly truncate.
function columnDdl(col: ColumnMeta, pk: string[]): string {
  const isPk = pk.includes(col.js);
  const type = col.type === "text" && !isPk ? "TEXT" : mysqlColumnType(col);
  const notNull = isPk ? " NOT NULL" : "";
  return `  \`${col.sql}\` ${type}${notNull}`;
}

export function createTableSql(spec: MysqlTableSpec): string {
  const lines = spec.columns.map((c) => columnDdl(c, spec.primaryKey));
  const singleAutoIncrementId = spec.primaryKey.length === 1 && spec.primaryKey[0] === "id" && !NO_AUTO_INCREMENT.has(spec.key);
  if (singleAutoIncrementId) {
    const idIndex = spec.columns.findIndex((c) => c.js === "id");
    lines[idIndex] = `  \`id\` INT NOT NULL AUTO_INCREMENT`;
  }
  const pkSql = `  PRIMARY KEY (${spec.primaryKey.map((js) => `\`${spec.columns.find((c) => c.js === js)!.sql}\``).join(", ")})`;
  return [
    `CREATE TABLE IF NOT EXISTS \`${spec.sqlName}\` (`,
    [...lines, pkSql].join(",\n"),
    `) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  ].join("\n");
}

function main() {
  const scopeArg = process.argv.find((a) => a.startsWith("--scope="))?.split("=")[1] ?? "all";
  const specs: MysqlTableSpec[] =
    scopeArg === "content" ? CONTENT_TABLE_SPECS : scopeArg === "users" ? USER_TABLE_SPECS : [...CONTENT_TABLE_SPECS, ...USER_TABLE_SPECS];

  const out: string[] = [];
  out.push("-- Auto-generated by scripts/src/mysql-restore/generateSchema.ts");
  out.push("-- Mirrors the MedSchoolProffs Postgres schema (lib/db/src/schema/medschool.ts)");
  out.push("-- so that a `formatVersion: 1` MedSchoolProffs backup JSON (see BACKUP_RESTORE.md)");
  out.push("-- can be loaded with scripts/src/mysql-restore/restore.ts. Run this once against a");
  out.push("-- fresh MySQL database before the first restore.");
  out.push("");
  out.push("SET NAMES utf8mb4;");
  out.push("");
  for (const spec of specs) {
    out.push(`-- ${spec.key}`);
    out.push(createTableSql(spec));
    out.push("");
  }
  process.stdout.write(out.join("\n"));
}

if (isEntryPoint()) main();
